image: dseg/node7-python2-pip-yarn-alpine35
pipelines:
    branches:
      staging:
        - step:
            script:
              - pip install awscli
              - yarn install
              - yarn run build-staging
              - aws s3 sync ./dist s3://staging.weathercheck.co
              - aws cloudfront create-invalidation --distribution-id EH2GJZBZHJ3V0 --paths '/*'
      master:
        - step:
            script:
              - pip install awscli
              - yarn install
              - yarn run build
              - aws s3 sync ./dist s3://app.weathercheck.co
              - aws cloudfront create-invalidation --distribution-id ESGH0GKSZA78E --paths '/*